### ISSUE TITLE
Some commentaries

### ISSUE THREAD

**Issue by marcocacciabue** [SantiFQ/mini-centrifugue#1]
I  recommend to keep all entries in English for more consistency (description is in English). Don´t forget to add photos in the repository of the process in the following days. Also please define clearly the objectives that you have decided to pursue.

**Comment by SantiFQ** [comment]
Thank you, Marco. We'll keep that in mind. The objectives that are now written are the ones we found more accurately correct, at the moment at least. 

Now we are looking forward to add photos of the days that we work together, and try to put some schematical images for the 3D model of the rotor and the lid of the centrifuge.
